# Generated by Django 4.1 on 2023-08-10 18:38

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='name', unique=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='DsaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.TextField(blank=True, max_length=300, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='question_name', unique=True)),
                ('c_language', tinymce.models.HTMLField(blank=True, null=True)),
                ('cpp_language', tinymce.models.HTMLField(blank=True, null=True)),
                ('javascript', tinymce.models.HTMLField(blank=True, null=True)),
                ('java', tinymce.models.HTMLField(blank=True, null=True)),
                ('python', tinymce.models.HTMLField(blank=True, null=True)),
                ('date', models.DateField()),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_questions.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'DSA Question',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='Tag Name')),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='name', unique=True)),
                ('date', models.DateField()),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_questions.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Sub Category',
            },
        ),
        migrations.CreateModel(
            name='SelectTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_questions.dsaquestion')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_questions.tags', verbose_name='Size')),
            ],
            options={
                'verbose_name_plural': 'Select Tag',
            },
        ),
        migrations.AddField(
            model_name='dsaquestion',
            name='sub_cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_questions.subcategory', verbose_name='SubCategory'),
        ),
    ]
