# Generated by Django 4.1 on 2023-08-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_questions', '0002_categoryadmin_dsaquestion_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryAdmin',
        ),
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dsaquestion',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
