# Generated by Django 4.1 on 2023-08-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_questions', '0003_delete_categoryadmin_alter_category_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='cat_id',
        ),
    ]
