# Generated by Django 4.1 on 2023-09-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_questions', '0004_remove_subcategory_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsaquestion',
            name='cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsa_questions.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='dsaquestion',
            name='sub_cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsa_questions.subcategory', verbose_name='SubCategory'),
        ),
        migrations.AlterField(
            model_name='selecttags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsa_questions.tags', verbose_name='Tag'),
        ),
    ]
