# Generated by Django 4.1 on 2023-01-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
    ]
