# Generated by Django 4.1 on 2023-01-15 14:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_comments_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
