# Generated by Django 4.1 on 2023-04-03 18:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_alter_blogpost_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, null=True, populate_from='title', unique=True),
        ),
    ]
