# Generated by Django 4.1.1 on 2023-01-01 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddImageWaterMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='add_watermark')),
                ('watermark_text', models.CharField(max_length=100)),
                ('on_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
