# Generated by Django 4.1 on 2023-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Contact',
            field=models.BigIntegerField(editable=None),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(editable=None, max_length=50),
        ),
    ]
