# Generated by Django 4.1.1 on 2023-01-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_qrcode_delete_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
