# Generated by Django 4.1 on 2023-01-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_color_alter_qrcode_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addimagewatermark',
            name='image',
        ),
        migrations.RemoveField(
            model_name='addimagewatermark',
            name='uid',
        ),
    ]
