# Generated by Django 4.1 on 2023-01-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_addimagewatermark_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=None, max_length=50)),
                ('email', models.CharField(editable=None, max_length=50)),
                ('Contact', models.CharField(editable=None, max_length=13)),
                ('message', models.TextField(editable=None)),
                ('on_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
